version: '3.8'

services:
  db:
    image: ankane/pgvector
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data # Mount the database data and tables

volumes:
  pgdata: